In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [3]:
print(a.ndim)    # Number of dimensions
print(a.shape)   # Shape
print(a.size)    # Number of elements
print(a.dtype)   # Data type

1
(5,)
5
int64


In [4]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
